#!/usr/bin/env php
<?php
namespace RWho;
require __DIR__."/lib-php/librwho.php";

function cleanup() {
	$max_age = 7200;

	$db = _open_db();

	$rows = $db->exec("DELETE FROM utmp WHERE updated < ".(time()-$max_age));
	if ($rows === false) {
		$err = $db->errorInfo();
		fwrite(STDERR, "error: ".implode("; ", $err)."\n");
	}
	return $rows;
}

if (cleanup() === false)
	exit(1);
