#!/usr/bin/env php
<?php

function rand_string($len) {
	$buf = random_bytes($len * 5);
	$buf = base64_encode($buf);
	$buf = preg_replace("/[^A-Za-z0-9]/", "", $buf);
	return substr($buf, 0, $len);
}

function rand_pass($glen=5, $ngrp=4, $sep="-") {
	$pw = rand_string($glen);
	while (--$ngrp) {
		$pw .= "-".rand_string($glen);
	}
	return $pw;
}

function make_salt($algo) {
	$salt = rand_string(CRYPT_SALT_LENGTH);
	return "\$$algo\$$salt\$";
}

$fqdn = @$argv[1] ?? "foo.example.com";

$passwd = rand_pass();
// Note: Usage of sha256crypt is deliberate, as these are verified during
//       every API call, but also are long enough to not be bruteforceable.
$digest = crypt($passwd, make_salt("5"));
#$digest = password_hash($passwd, PASSWORD_DEFAULT);

echo "\e[1m# Client (/etc/rwho/agent.conf)\e[m\n";
echo "[agent]\n";
echo "auth_password = $passwd\n";
echo "\n";

echo "\e[1m# Server (".__DIR__."/server.conf)\e[m\n";
echo "[auth.pw]\n";
echo "$fqdn = $digest\n";
echo "\n";
