#!/usr/bin/env php
<?php

function rand_string($len) {
	$buf = random_bytes($len * 5);
	$buf = base64_encode($buf);
	$buf = preg_replace("/[^A-Za-z0-9]/", "", $buf);
	return substr($buf, 0, $len);
}

function rand_pass($glen=5, $ngrp=4, $sep="-") {
	$pw = rand_string($glen);
	while (--$ngrp) {
		$pw .= "-".rand_string($glen);
	}
	return $pw;
}

function make_salt($algo) {
	$salt = rand_string(CRYPT_SALT_LENGTH);
	return "\$$algo\$$salt\$";
}

$fqdn = @$argv[1];
if (!strlen($fqdn)) {
	fwrite(STDERR, "error: hostname not specified\n");
	exit(1);
}

$pw = rand_pass();
echo "; client\n", "agent.auth_password = $pw\n", "\n";

#$dg = password_hash($pw, PASSWORD_DEFAULT);
$dg = crypt($pw, make_salt("5"));
echo "; server\n", "auth.pw.$fqdn = $dg\n";
