#!/usr/bin/env bash
# rwho - simple 'finger' client hardcoded to query a rwho-ng server

[[ $DEBUG ]] && set -x

RWHO_DIR="/cluenet/rwho"

RWHO_HOST='rwho.cluenet.org'
RWHO_URL="http://$RWHO_HOST/"

CONFIG="$RWHO_DIR/rwho.conf"

if [[ -s $CONFIG ]]; then
	re='^\s*([^;#][^\s]+)\s*=\s*(.*)$'
	while read -r line; do
		if [[ $line =~ $re ]]; then
			key=${BASH_REMATCH[1]}
			val=${BASH_REMATCH[2]}
			case $key in
			'finger.host')
				RWHO_HOST=$val;;
			'finger.port')
				RWHO_PORT=$val;;
			'agent.notify_url')
				RWHO_URL=${val#server.php};;
			esac
		fi
	done < "$CONFIG"
fi

PLAN_URL="${RWHO_URL%/}/update-plan.php?user=$(logname)"

usage() {
	echo "Usage: ${0##*/} [-l] [-v] [-G|-P file|-D|-e] [user][@host]"
	echo ""
	echo "  -l  list hosts"
	echo "  -v  verbose output"
	echo ""
	echo "  -G  get plan to stdout"
	echo "  -P  put plan file"
	echo "  -D  delete plan"
	echo "  -e  get, edit & reupload plan"
	echo ""
	echo "HTTP interface is available at: $RWHO_URL"
	echo ""
	echo "This version of rwho was developed by grawity <grawity@gmail.com>"
	exit 2
}

filter() {
	perl -pe 's/\033/"^".chr(ord($&)+0100)/ge'
}

conn() {
	local host=$1 request=$2 fd=
	exec {fd}<>"/dev/tcp/$host/finger" || {
		echo >&2 "rwho: connection failed ($?)"
		return 1
	}
	printf >&$fd '%s\r\n' "$request"
	filter <&$fd
	exec {fd}>&-
}

action='query'
file=
opt_l=false
hosts=false
long=false

while getopts ":GDP:elv" OPT; do
	case $OPT in
	'G')	action='plan-print';;
	'D')	action='plan-delete';;
	'P')	action='plan-put'; file=$OPTARG;;
	'e')	action='plan-edit';;
	'l')	opt_l=true;;
	'v')	long=true;;
	'?')	echo "Unknown option '$OPTARG'" >&2;
		usage;;
	':')	echo "Missing argument for -$OPTARG" >&2;
		usage;;
	esac
done
shift $((OPTIND-1))

case $action in
'query')
	host=$RWHO_HOST
	query=$1
	if $opt_l; then
		if [[ $query ]]; then
			long=true
			query="/W $query"
		else
			hosts=true
			query="*"
		fi
	fi
	if [[ $query == *@* ]]; then
		qhost=${query##*@}
		if [[ $qhost == *.* ]]; then
			host=$qhost
			query=${query%@*}
		fi
	fi
	conn "$host" "$query"
	;;
'plan-print')
	curl "$PLAN_URL" -sfS
	;;
'plan-put')
	curl "$PLAN_URL" -T "$file" -sfS
	;;
'plan-edit')
	temp=$(mktemp ~/rwho-plan.XXXXXXXX)
	curl "$PLAN_URL" -o "$temp" -s
	$EDITOR "$temp"
	head=$(head -c 16 "$temp")
	if [[ ! $head || $head == "No Plan." ]]; then
		curl "$PLAN_URL" -X DELETE -sfS
	else
		curl "$PLAN_URL" -T "$temp" -sfS
	fi
	rm -f "$temp"
	;;
'plan-delete')
	curl "$PLAN_URL" -X DELETE -sfS
	;;
esac
