#!/usr/bin/env bash
# rwho - simple 'finger' client hardcoded to query a rwho-ng server

[[ $DEBUG ]] && set -x

RWHO_DIR="/etc/rwho"

declare -A config=()

if [[ -s "$RWHO_DIR/rwho.conf" ]]; then
	cre='^[^;#]'
	sre='^\[([^\s]+)\]$'
	are='^([^\s]+)\s*=\s*(.*)$'
	section=''
	while read -r line; do
		if ! [[ $line =~ $cre ]]; then
			continue
		elif [[ $line =~ $sre ]]; then
			section=${BASH_REMATCH[1]}
		elif [[ $line =~ $are ]]; then
			key=${BASH_REMATCH[1]}
			val=${BASH_REMATCH[2]}
			config["$section$key"]=$val
		fi
	done < "$RWHO_DIR/rwho.conf"
fi

RWHO_HOST='rwho.nullroute.lt'
if [[ ${config['finger.host']} ]]; then
	RWHO_HOST=${config['finger.host']}
fi

usage() {
	echo "Usage: ${0##*/} [-l] [-v] [user][@host]"
	echo ""
	echo "  -l  list hosts"
	echo "  -v  verbose output"
	echo ""
	echo "This version of rwho was developed by grawity <grawity@gmail.com>"
	exit 2
}

filter() {
	perl -pe 's/\033/"^".chr(ord($&)+0100)/ge'
}

conn() {
	local host=$1 request=$2 fd=
	exec {fd}<>"/dev/tcp/$host/finger" || {
		echo >&2 "rwho: connection failed ($?)"
		return 1
	}
	printf >&$fd '%s\r\n' "$request"
	filter <&$fd
	exec {fd}>&-
}

action='query'
opt_l=false
hosts=false
long=false

while getopts ":lv" OPT; do
	case $OPT in
	'l')	opt_l=true;;
	'v')	long=true;;
	'?')	echo "Unknown option '$OPTARG'" >&2;
		usage;;
	esac
done
shift $((OPTIND-1))

case $action in
'query')
	host=$RWHO_HOST
	query=$1

	if $opt_l; then
		if [[ $query ]]; then
			long=true
		else
			query="*"
		fi
	fi

	if $long; then
		query="/W $query"
	fi

	if [[ $query == *@* ]]; then
		qhost=${query##*@}
		if [[ $qhost == *.* ]]; then
			host=$qhost
			query=${query%@*}
		fi
	fi

	conn "$host" "$query"
	;;
esac
